/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  cpsorder: () => import("@/views/cpsorder/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "manage_coupon-link-category": () => import("@/views/manage/coupon-link-category/index.vue"),
  "manage_coupon-link": () => import("@/views/manage/coupon-link/index.vue"),
  wechatfans_employees: () => import("@/views/wechatfans/employees/index.vue"),
  wechatfans_fans: () => import("@/views/wechatfans/fans/index.vue"),
  wechatfans_qrcode: () => import("@/views/wechatfans/qrcode/index.vue"),
  wechatfans_tags: () => import("@/views/wechatfans/tags/index.vue"),
  wechatfans_wechatmanage: () => import("@/views/wechatfans/wechatmanage/index.vue"),
};
