/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'getcouponmanage',
    path: '/getcouponmanage',
    component: 'layout.base',
    meta: {
      title: '领券管理',
      i18nKey: '领券管理',
      icon: 'hugeicons:coupon-percent',
      order: 2
    },
    children: [
      {
        name: 'getcouponmanage_coupon-link',
        path: '/getcouponmanage/coupon-link',
        component: 'view.getcouponmanage_coupon-link',
        meta: {
          title: '链接列表',
          i18nKey: '链接列表',
          icon: 'ri:coupon-3-fill',
          order: 3
        }
      },
      {
        name: 'getcouponmanage_coupon-link-category',
        path: '/getcouponmanage/coupon-link-category',
        component: 'view.getcouponmanage_coupon-link-category',
        meta: {
          title: '分类列表',
          i18nKey: '分类列表',
          order: 2,
          icon: 'material-symbols:category'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      hideInMenu: true,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 3
    },
    children: [
      {
        name: 'manage_button',
        path: '/manage/button',
        component: 'view.manage_button',
        meta: {
          title: '按钮管理',
          i18nKey: '按钮管理',
          icon: 'material-symbols-light:radio-button-checked-outline'
        }
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route'
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role'
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts'
        }
      }
    ]
  }
];
