/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'cpsorder',
    path: '/cpsorder',
    component: 'layout.base$view.cpsorder',
    meta: {
      title: 'cpsorder',
      i18nKey: 'route.cpsorder',
      icon: 'material-symbols:draft-orders'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      roles: ['R_SUPER']
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 9
    },
    children: [
      {
        name: 'manage_coupon-link',
        path: '/manage/coupon-link',
        component: 'view.manage_coupon-link',
        meta: {
          title: '领券链接管理',
          i18nKey: '领券链接管理'
        }
      },
      {
        name: 'manage_coupon-link-category',
        path: '/manage/coupon-link-category',
        component: 'view.manage_coupon-link-category',
        meta: {
          title: '领券链接分类管理',
          i18nKey: '领券链接分类管理'
        }
      }
    ]
  },
  {
    name: 'wechatfans',
    path: '/wechatfans',
    component: 'layout.base',
    meta: {
      title: 'wechatfans',
      i18nKey: 'route.wechatfans',
      icon: 'ant-design:wechat-work-filled'
    },
    children: [
      {
        name: 'wechatfans_employees',
        path: '/wechatfans/employees',
        component: 'view.wechatfans_employees',
        meta: {
          title: 'wechatfans_employees',
          i18nKey: 'route.wechatfans_employees',
          icon: 'clarity:employee-group-solid'
        }
      },
      {
        name: 'wechatfans_fans',
        path: '/wechatfans/fans',
        component: 'view.wechatfans_fans',
        meta: {
          title: 'wechatfans_fans',
          i18nKey: 'route.wechatfans_fans',
          icon: 'fluent:people-audience-32-filled'
        }
      },
      {
        name: 'wechatfans_qrcode',
        path: '/wechatfans/qrcode',
        component: 'view.wechatfans_qrcode',
        meta: {
          title: 'wechatfans_qrcode',
          i18nKey: 'route.wechatfans_qrcode',
          icon: 'uil:qrcode-scan'
        }
      },
      {
        name: 'wechatfans_tags',
        path: '/wechatfans/tags',
        component: 'view.wechatfans_tags',
        meta: {
          title: 'wechatfans_tags',
          i18nKey: 'route.wechatfans_tags',
          icon: 'material-symbols:label'
        }
      },
      {
        name: 'wechatfans_wechatmanage',
        path: '/wechatfans/wechatmanage',
        component: 'view.wechatfans_wechatmanage',
        meta: {
          title: 'wechatfans_wechatmanage',
          i18nKey: 'route.wechatfans_wechatmanage',
          icon: 'material-symbols:enterprise'
        }
      }
    ]
  }
];
